baseURL: "https://karthikmacherla.com"
title: "Karthik Macherla"
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

googleAnalytics: G-5M9VCY5HPE

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Hi, I'm Karthik! \U0001F44B"
  description: "Welcome to my blog"
  author: Me
  # author: ["Me", "You"] # multiple authors

  images: "<link or path of image for opengraph, twitter-cards>"

  ShowReadingTime: true
  ShowShareButtons: false
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    faviconApple: /img/logodarkgoldicon.png
    favicon: /img/logodarkgold.png

  label:
    text: "Karthik Macherla"
    iconlight: /img/logolightgold.png
    icondark: /img/logodarkgold.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi, I'm Karthik! \U0001F44B"
    imageUrl: "img/blackshirt.jpg"
    # imageTitle: my image
    buttons:
      - name: Projects
        url: tags/projects
      - name: Thoughts
        url: tags/thoughts
      - name: All Posts
        url: /archives/
      # - name: Subscribe!
      #   url: http://eepurl.com/hy1YIv

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Karthik! \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: instagram
      url: "https://instagram.com/karthik.macherla"
    - name: linkedin
      url: "https://linkedin.com/in/karthikmacherla"
    - name: github
      url: "https://github.com/karthikmacherla"
    - name: rss
  analytics:
    google:
      SiteVerificationTag: "G-5M9VCY5HPE"

menu:
  main:
    - name: Projects
      url: /tags/projects/
      weight: 2
    - name: Thoughts
      url: /tags/thoughts/
      weight: 3
    # - name: Archive
    #   url: /archives/
    #   weight: 5
    - name: About
      url: /about/
      weight: 6
    - name: Subscribe
      url: http://eepurl.com/hy1YIv
      weight: 7